package coen359.vendingmachine.product;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.border.TitledBorder;

import coen359.vendingmachine.admin.ManagementView;
import coen359.vendingmachine.admin.LoginView;

import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * Updated GUI
 * The view for the product table. 
 *
 * @author farza
 */

public class ProductView extends javax.swing.JFrame {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private JTable jtable1; // the table displayed on the GUI
	private ProductController productTableController; // glue between model and gui
	

	public ProductView(){
		setTitle("PRODUCT MANAGEMENT");
		setIconImage(Toolkit.getDefaultToolkit().getImage(ProductView.class.getResource("/coen359/vendingmachine/resources/Vending Machine.png")));
		setBackground(new Color(245, 245, 220));
		setSize(1200, 600);
		initComponents();
		jPanel1.setPreferredSize(new Dimension(400, 550));
		productTableController = new ProductController(this);
		addJTable();
	}

	// creates a table and adds it to the GUI. 
	// Attaches the controller as a listener to the table
	public void addJTable() {
		// add the data and column names to a JTable
		jtable1 = new JTable(productTableController.getTableModel());
		jtable1.getTableHeader().setFont(new Font("Trebuchet MS", Font.PLAIN, 28));
		jtable1.setRowHeight(30);
		jtable1.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));

		// add a ListSelectionListener to the table
		jtable1.getSelectionModel().addListSelectionListener(productTableController);

		// add the table to a scrollpane
		JScrollPane scrollpane = new JScrollPane(jtable1);

		// create a window
		jPanel2.setLayout(new BorderLayout());
		jPanel2.add(scrollpane, BorderLayout.CENTER);
		jPanel2.setPreferredSize(new Dimension(500, 750));
	}

	public void updateTable() {
		jtable1.setModel(productTableController.getTableModel());
	}

	public void setTypeComboBox(String type) {
		typeComboBox.setSelectedItem(type);
	}
	
	// display data on the idTextField
	public void setIdTextField(String value) {
		idTextField.setText(value);
	}

	// display data on the nameTextField
	public void setNameTextField(String value) {
		nameTextField.setText(value);
	}

	// display data on the priceTextField
	public void setPriceTextField(String value) {
		priceTextField.setText(value);
	}

	// display data on the expiryDateTextField
	public void setExpiryDateTextField(String value){

		if(value == null)
			expiryDateTextField.setValue("");

		else{

			try {
				
				final DateFormat inputFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy");
				
				// The parsed date
				final Date parsed = inputFormat.parse(value);

				// The output format. Specify the one needed.
				final DateFormat outputFormat1 = new SimpleDateFormat("dd-MM-yyyy");

				expiryDateTextField.setValue(outputFormat1.format(parsed));
			} 
			catch (ParseException e) {
				
				expiryDateTextField.setValue("");
			}
		}

	}
	// display data on the quantityTextField
	public void setQuantityTextField(String value) {
		quantityTextField.setText(value);
	}

	// display data on the imageLinkTextField
	public void setImageLinkTextField(String value) {
		imageLinkTextField.setText(value);
	}

	//display data on the calorieTextField
	public void setCalorieTextField(String value) {
		calorieTextField.setText(value);
	}

	// display data on the sugarTextField
	public void setSugarTextField(String value) {
		sugarTextField.setText(value);
	}

	//display data on the fatTextField
	public void setFatTextField(String value) {
		fatTextField.setText(value);
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void initComponents() {

		jPanel4 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(Color.BLACK);
		jLabel1.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		jLabel2 = new javax.swing.JLabel();
		jLabel2.setForeground(Color.BLACK);
		jLabel2.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		jLabel3 = new javax.swing.JLabel();
		jLabel3.setForeground(Color.BLACK);
		jLabel3.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		jLabel4 = new javax.swing.JLabel();
		jLabel4.setForeground(Color.BLACK);
		jLabel4.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		idTextField = new javax.swing.JTextField();
		idTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));

		nameTextField = new javax.swing.JTextField();
		nameTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));

		priceTextField = new javax.swing.JTextField();
		priceTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));

		expiryDateTextField = new javax.swing.JFormattedTextField();
		expiryDateTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));

		addButton = new javax.swing.JButton();
		addButton.setFont(new Font("Trebuchet MS", Font.PLAIN, 20));

		deleteButton = new javax.swing.JButton();
		deleteButton.setFont(new Font("Trebuchet MS", Font.PLAIN, 20));

		clearButton = new javax.swing.JButton();
		clearButton.setFont(new Font("Trebuchet MS", Font.PLAIN, 20));

		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBackground(Color.WHITE);
		jPanel2.setForeground(Color.BLUE);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE)
				);
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE)
				);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "PRODUCT MANAGEMENT", TitledBorder.CENTER, TitledBorder.TOP, null, new Color(0, 0, 0)));

		jLabel1.setText("Product Id");

		jLabel2.setText("Product Name");

		jLabel3.setText("Product Price");

		jLabel4.setText("Expiry Date");

		idTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				idTextFieldActionPerformed(evt);
			}
		});

		nameTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameTextFieldActionPerformed(evt);
			}
		});

		expiryDateTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				expiryDateTextFieldActionPerformed(evt);
			}
		});

		addButton.setText("ADD PRODUCT");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					String s = "";
					boolean exists = false;

					if (idTextField.getText().equals("") || nameTextField.getText().equals("") || priceTextField.getText().equals("") || expiryDateTextField.getText().equals("") || fatTextField.getText().equals("") || sugarTextField.getText().equals("")|| calorieTextField.getText().equals("")  ) {
						UIManager.put("OptionPane.minimumSize",new Dimension(500,200)); 							
						UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 26));
						JOptionPane.showMessageDialog(null, "Please enter entire product details.");
						clearButtonActionPerformed(evt); 
					}

					for (int i = 0; i < jtable1.getRowCount(); i++) {

						s = jtable1.getValueAt(i, 0).toString().trim();

						if (idTextField.getText().equals(s)) {
							exists = true;
							UIManager.put("OptionPane.minimumSize",new Dimension(500,200)); 							
							UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 26));
							JOptionPane.showMessageDialog(null, "Duplicate entries not allowed");	
							clearButtonActionPerformed(evt); 
							break;
						}
					}

					if (!exists) {					
						
				
						addButtonActionPerformed(evt);
						clearButtonActionPerformed(evt); 
						
						UIManager.put("OptionPane.minimumSize",new Dimension(500,200)); 							
						UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 26));
						JOptionPane.showMessageDialog(null, "Product added successfully!");

					} 

				} 

				catch (NumberFormatException e) {
					e.printStackTrace();
				} 

				catch (ParseException e) {
					e.printStackTrace();
				}
			}
		});


		JButton btnUpdateProduct = new JButton("UPDATE PRODUCT");
		btnUpdateProduct.setFont(new Font("Trebuchet MS", Font.PLAIN, 20));
		btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					
					if (idTextField.getText().equals("") || nameTextField.getText().equals("") || priceTextField.getText().equals("") || expiryDateTextField.getText().equals("") || fatTextField.getText().equals("") || sugarTextField.getText().equals("")|| calorieTextField.getText().equals("")  ) {
						UIManager.put("OptionPane.minimumSize",new Dimension(500,200)); 							
						UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 26));
						JOptionPane.showMessageDialog(null, "Please enter entire product details.");
						clearButtonActionPerformed(evt); 
					}

					else{		
						
						
						updateButtonActionPerformed(evt);
						clearButtonActionPerformed(evt); 
						
						UIManager.put("OptionPane.minimumSize",new Dimension(500,200)); 							
						UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 26));
						JOptionPane.showMessageDialog(null, "Product Updated.");
					}
						

					} 
				

				catch (NumberFormatException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		deleteButton.setText("DELETE PRODUCT");
		deleteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
						
				deleteButtonActionPerformed(evt);
				clearButtonActionPerformed(evt);
				
				UIManager.put("OptionPane.minimumSize",new Dimension(500,200)); 							
				UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 26));
				JOptionPane.showMessageDialog(null, "Product Deleted.");
			}
		});

		clearButton.setText("CLEAR");
		clearButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearButtonActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 807, Short.MAX_VALUE)
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 172, Short.MAX_VALUE) 
				);

		lblProductType = new JLabel("Product Type");
		lblProductType.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));

		typeComboBox = new JComboBox();
		typeComboBox.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));
		typeComboBox.setModel(new DefaultComboBoxModel(new String[] {"Candy", "Sandwich", "Beverage"}));

		lblFat = new JLabel("Fat");
		lblFat.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		fatTextField = new JTextField();
		fatTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));
		fatTextField.setColumns(10);

		lblCalorie = new JLabel("Calorie");
		lblCalorie.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		sugarTextField = new JTextField();
		sugarTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));
		sugarTextField.setColumns(10);

		lblSugar = new JLabel("Sugar");
		lblSugar.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		calorieTextField = new JTextField();
		calorieTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		lblQuantity = new JLabel("Quantity");
		lblQuantity.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		quantityTextField = new JTextField();
		quantityTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));


		lblImageLink = new JLabel("Image Link");
		lblImageLink.setFont(new Font("Trebuchet MS", Font.PLAIN, 24));

		imageLinkTextField = new JTextField();
		imageLinkTextField.setFont(new Font("Trebuchet MS", Font.PLAIN, 22));
		imageLinkTextField.setColumns(10);
		
		btnHome = new JButton("Home");
		btnHome.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				setVisible(false);
				new ManagementView().setVisible(true);
			}
		});
		btnHome.setFont(new Font("Trebuchet MS", Font.BOLD, 22));
		
		btnLogOut = new JButton("Log Out");
		btnLogOut.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				setVisible(false);
				LoginView.main(null);	
				
			}
		});
		btnLogOut.setFont(new Font("Trebuchet MS", Font.BOLD, 22));
		
		JButton backButton = new JButton("Back");
		backButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				setVisible(false);
				new ManagementView().setVisible(true);
			}
		});
		backButton.setFont(new Font("Trebuchet MS", Font.BOLD, 22));


		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
							.addGap(27)
							.addComponent(btnLogOut)
							.addGap(18)
							.addComponent(backButton, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
							.addGap(1593))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
									.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
											.addComponent(jLabel3)
											.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
											.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
											.addComponent(lblFat, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
											.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
												.addComponent(lblImageLink, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
											.addComponent(lblProductType, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
										.addGap(36)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
											.addGroup(jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
													.addComponent(imageLinkTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(quantityTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(fatTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(priceTextField, Alignment.LEADING, 268, 268, Short.MAX_VALUE)
													.addComponent(nameTextField, Alignment.LEADING, 268, 268, Short.MAX_VALUE)
													.addComponent(idTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(expiryDateTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(calorieTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(sugarTextField, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
													.addComponent(addButton, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
													.addComponent(btnUpdateProduct, Alignment.LEADING)
													.addComponent(deleteButton, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
													.addComponent(clearButton, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
												.addGap(188))
											.addComponent(typeComboBox, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE))
										.addGap(45))
									.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
											.addComponent(lblSugar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
											.addComponent(lblCalorie, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
										.addPreferredGap(ComponentPlacement.RELATED)))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addComponent(lblQuantity)
									.addPreferredGap(ComponentPlacement.RELATED)))
							.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 1033, GroupLayout.PREFERRED_SIZE)
							.addGap(185))))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
							.addComponent(btnHome, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(btnLogOut, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addComponent(backButton, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
					.addGap(9)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 880, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(62)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblProductType, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
								.addComponent(typeComboBox, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
							.addGap(26)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(idTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
							.addGap(28)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(priceTextField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
							.addGap(31)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
								.addComponent(expiryDateTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblFat, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
								.addComponent(fatTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblCalorie, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
								.addComponent(calorieTextField, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblSugar, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
								.addComponent(sugarTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblQuantity, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
								.addComponent(quantityTextField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(imageLinkTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblImageLink, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
							.addGap(43)
							.addComponent(addButton, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(btnUpdateProduct, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(clearButton, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 2000, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(30, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
						.addContainerGap())
				);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>                        

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
		idTextField.setText("");
		nameTextField.setText("");
		priceTextField.setText("");
		expiryDateTextField.setText("");
		fatTextField.setText("");
		sugarTextField.setText("");
		calorieTextField.setText("");
		quantityTextField.setText("");
		imageLinkTextField.setText("");
		calorieTextField.setText("");
		sugarTextField.setText("");
		fatTextField.setText("");

	}                                            

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             

		String[] array = new String[jtable1.getColumnCount()]; 
		array[0] = idTextField.getText();
		array[1] = nameTextField.getText();
		array[2] = priceTextField.getText();
		array[3] = expiryDateTextField.getText();

		array[4] = quantityTextField.getText();
		array[5] = (String)typeComboBox.getSelectedItem( );
		array[6] = imageLinkTextField.getText();

		array[7] = fatTextField.getText();
		array[8] = sugarTextField.getText();
		array[9] = calorieTextField.getText();	

		productTableController.deleteRow(array);

	}                                            

	// code for the Add button
	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, ParseException {                                          

		//add a row to the table
		//String[] array = new String[jtable1.getColumnCount() + jtable2.getColumnCount()];

		//System.out.println("jtable column count" +jtable1.getColumnCount());
		String[] array = new String[jtable1.getColumnCount()];

		array[0] = idTextField.getText();
		array[1] = nameTextField.getText();
		array[2] = priceTextField.getText();
		array[3] = expiryDateTextField.getText();
		array[4] = quantityTextField.getText();
		array[5] = (String)typeComboBox.getSelectedItem( );
		array[6] = imageLinkTextField.getText();

		array[7] = calorieTextField.getText();
		array[8] = fatTextField.getText();
		array[9] = sugarTextField.getText();	

		productTableController.addRow( array);


	}            


	private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, ParseException {                                          

		//add a row to the table
		String[] array = new String[jtable1.getColumnCount()];

		array[0] = idTextField.getText();
		array[1] = nameTextField.getText();
		array[2] = priceTextField.getText();
		array[3] = expiryDateTextField.getText();
		array[4] = quantityTextField.getText();
		array[5] = (String)typeComboBox.getSelectedItem( ); // have to change this to the value retrieved from the jtable
		array[6] = imageLinkTextField.getText();

		array[7] = calorieTextField.getText();
		array[8] = fatTextField.getText();
		array[9] = sugarTextField.getText();	


		productTableController.updateRow( array);


	}   

	private void expiryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
		// TODO add your handling code here:
	}                                                  

	private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                      
		// TODO add your handling code here:
	}                                                     

	private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
		// TODO add your handling code here:
	}                                                   

	// Variables declaration - do not modify                     
	private javax.swing.JButton addButton;
	private javax.swing.JButton deleteButton;
	private javax.swing.JButton clearButton;

	private javax.swing.JTextField idTextField;
	private javax.swing.JTextField nameTextField;	
	private javax.swing.JTextField priceTextField;
	private javax.swing.JFormattedTextField expiryDateTextField;
	private JTextField fatTextField;	
	private JTextField sugarTextField;	
	private JTextField calorieTextField;
	private JTextField quantityTextField;
	private JTextField imageLinkTextField;

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private JLabel lblProductType;
	private JLabel lblFat;
	private JLabel lblCalorie;
	private JLabel lblSugar;
	private JLabel lblQuantity;
	private JLabel lblImageLink;


	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;	

	private JComboBox<String> typeComboBox;
	private JButton btnHome;
	private JButton btnLogOut;
}


